version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 17012005
      MYSQL_DATABASE: securing_web
    ports:
      - "3307:3306"   # Host:Container
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: springapp
    ports:
      - "9090:8080"   # Host:Container
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  mysql_data:
