# =========================
# MySQL Deployment + Service
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: securingdb
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  # để Spring Boot có thể kết nối qua DNS ổn định
---
# =========================
# Spring Boot Deployment + Service
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securing-web-deployment
spec:
  selector:
    matchLabels:
      app: securing-web
  replicas: 3
  template:
    metadata:
      labels:
        app: securing-web
    spec:
      containers:
        - name: securing-web
          image: securing-web-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/securingdb
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: securing-web-service
spec:
  selector:
    app: securing-web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
