apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: securing-web
  namespace: argocd   # ArgoCD phải được cài trong namespace này
spec:
  project: default

  source:
    repoURL: https://github.com/thanhha-haha/securing-web.git   # 🔹 Repo chứa file YAML triển khai
    targetRevision: master                                                        # 🔹 Branch cần deploy
    path: securing-web/argocd                                                                   # 🔹 Thư mục chứa deployment.yaml, service.yaml,...

  destination:
    server: https://kubernetes.default.svc
    namespace: default                                                          # 🔹 Namespace muốn deploy app vào

  syncPolicy:
    automated:
      prune: true       # Xóa các resource không còn trong Git repo
      selfHeal: true    # Nếu có thay đổi ngoài Git, ArgoCD tự sửa lại
    syncOptions:
      - CreateNamespace=true
