name: CI Pipeline

on:
  push:
    branches: [ thanhha-haha-patch-1 ]   # chạy khi push lên nhánh này

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug secrets
        run: |
          echo "🔍 Username: ${{ secrets.DOCKER_USERNAME }}"
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "❌ Password is EMPTY or not found in secrets!"
          else
            echo "✅ Password length: ${#${{ secrets.DOCKER_PASSWORD }}}"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/securing-web-app:latest
